Repository prgrms-fe-devcourse/FES-5-Project3-TEAM-4, pull requests merged in 2025-08, with the labels that each got.

#9 Feat/register 회원가입 기능개발
  index.html
  public/icons/info.svg
  src/common/api/auth/register.ts
  src/common/components/.gitkeep
  src/common/components/AuthForm.tsx
  src/common/components/AuthLayout.tsx
  src/common/components/AuthValidate.tsx
  src/common/components/EmailField.tsx
  src/common/components/PasswordField.tsx
  src/pages/Auth/Login.tsx
  src/pages/Auth/Register.tsx
  src/pages/Login/components/EmailField.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/Login/components/PasswordField.tsx
  src/pages/Login/index.tsx
  src/pages/Register/components/RegisterForm.tsx
  src/pages/Register/index.tsx
  src/router/routes.tsx
  src/styles/_base.css
Labels: Feature, Design

#22 feat : 타로 질문 페이지 틀 제작
  public/icons/health.svg
  public/icons/liked.svg
  public/icons/money.svg
  public/icons/question.svg
  public/icons/study.svg
  public/icons/submit.svg
  public/icons/work.svg
  src/assets/crystal_sphere.png
  src/assets/crystal_sphere_mask.svg
  src/assets/crystal_sphere_overlay.svg
  src/common/types/TarotTopics.ts
  src/pages/Tarot/index.tsx
  src/pages/TarotQuestion/components/CrystalBallLetters.tsx
  src/pages/TarotQuestion/components/CrystalBallStage.tsx
  src/pages/TarotQuestion/components/QuestionExamples.tsx
  src/pages/TarotQuestion/components/TopicButton.tsx
  src/pages/TarotQuestion/components/TopicPrompt.tsx
  src/pages/TarotQuestion/index.tsx
Labels: Feature

#28 style : 타로 셔플 페이지 틀 제작
  src/assets/Tarot/crystal_sphere.png
  src/assets/Tarot/crystal_sphere_mask.svg
  src/assets/Tarot/crystal_sphere_overlay.svg
  src/assets/Tarot/icons/health.svg
  src/assets/Tarot/icons/liked.svg
  src/assets/Tarot/icons/money.svg
  src/assets/Tarot/icons/question.svg
  src/assets/Tarot/icons/spread.svg
  src/assets/Tarot/icons/study.svg
  src/assets/Tarot/icons/submit.svg
  src/assets/Tarot/icons/work.svg
  src/assets/Tarot/tarot_cards.svg
  src/pages/Tarot/index.tsx
  src/pages/TarotQuestion/components/CrystalBallLetters.tsx
  src/pages/TarotQuestion/components/TopicPrompt.tsx
  src/pages/TarotQuestion/index.tsx
  src/pages/TarotShuffle/components/ShuffleCards.tsx
  src/pages/TarotShuffle/components/StopShuffleBtn.tsx
  src/pages/TarotShuffle/index.tsx
Labels: Design

#31 feat, style : 타로 카드 컴포넌트 제작 및 3D배경 기초 작업
  package.json
  public/velvet.png
  public/wall.png
  src/assets/Tarot/tarot_back.svg
  src/assets/Tarot/tarot_front.svg
  src/pages/Tarot/components/SceneGeometry.tsx
  src/pages/Tarot/components/TarotCard.tsx
  src/pages/Tarot/components/TarotTableScene.tsx
  src/pages/Tarot/components/TarotTiltPage.tsx
Labels: Feature, Design

#32 Feat/password reset kym
  package.json
  src/common/api/Profile/profile.ts
  src/common/api/auth/login.ts
  src/common/api/auth/register.ts
  src/common/api/auth/resetPassword.ts
  src/common/components/AuthForm.tsx
  src/common/components/EmailField.tsx
  src/common/components/PasswordField.tsx
  src/common/layouts/Header.tsx
  src/common/utils/sweetalert.ts
  src/pages/ForgotPassword/components/EmailVerify.tsx
  src/pages/ForgotPassword/index.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/Login/components/OAuthCallback.tsx
  src/pages/PasswordReset/components/NewPassword.tsx
  src/pages/PasswordReset/index.tsx
  src/pages/Register/components/RegisterForm.tsx
  src/router/routes.tsx
Labels: Feature

#37 Feat/mypage post like kym
  .vscode/settings.json
  public/icons/stargroup.svg
  src/common/api/Community/community.ts
  src/common/api/Likes/likes.ts
  src/common/api/Profile/profile.ts
  src/common/api/supabase/database.types.ts
  src/common/store/authStore.ts
  src/pages/Login/components/OAuthCallback.tsx
  src/pages/Mypage/components/BoardItem.tsx
  src/pages/Mypage/components/Likes.tsx
  src/pages/Mypage/components/Post.tsx
  src/pages/Mypage/components/Record.tsx
  src/pages/Mypage/components/RecordItem.tsx
Labels: Feature

#39 feat : TarotCard - 컴포넌트 재구성 및 타입 추가
  src/pages/Tarot/components/TarotCard.tsx
  src/pages/Tarot/hooks/useApplyTransforms.ts
  src/pages/Tarot/hooks/useCardDrag.ts
  src/pages/Tarot/hooks/useCardFlip.ts
  src/pages/Tarot/hooks/useCardHover.ts
  src/pages/Tarot/types/CardProps.ts
Labels: Feature
