Repository prgrms-fe-devcourse/FES-5-Project3-TEAM-4, pull requests merged in 2025-09, with the labels that each got.

#45 feat : 타로 카드 스프레드 & 드로우
  src/assets/Tarot/icons/draw.svg
  src/assets/Tarot/icons/warning.svg
  src/pages/Tarot/components/TarotCard.tsx
  src/pages/Tarot/hooks/useCardDrag.ts
  src/pages/Tarot/index.tsx
  src/pages/Tarot/store/tarotStore.ts
  src/pages/Tarot/types/CardProps.ts
  src/pages/TarotQuestion/index.tsx
  src/pages/TarotResult/components/DrawMoreBtn.tsx
  src/pages/TarotResult/components/DrawMoreMsg.tsx
  src/pages/TarotResult/components/ResultCardMain.tsx
  src/pages/TarotResult/components/ResultCardPair.tsx
  src/pages/TarotResult/components/ResultCardSub.tsx
  src/pages/TarotResult/index.tsx
  src/pages/TarotResult/utils/ambiguous.ts
  src/pages/TarotShuffle/components/StopShuffleBtn.tsx
  src/pages/TarotShuffle/index.tsx
  src/pages/TarotSpreadDraw/components/DrawMainSlot.tsx
  src/pages/TarotSpreadDraw/components/DrawSlot.tsx
  src/pages/TarotSpreadDraw/components/DrawSlotPair.tsx
  src/pages/TarotSpreadDraw/components/DrawSubSlot.tsx
  src/pages/TarotSpreadDraw/components/Spread.tsx
  src/pages/TarotSpreadDraw/components/TarotSpread.tsx
  src/pages/TarotSpreadDraw/hooks/useElementSize.ts
  src/pages/TarotSpreadDraw/hooks/useTarotDeck.ts
  src/pages/TarotSpreadDraw/index.tsx
  src/pages/TarotSpreadDraw/utils/cardHelpers.ts
  src/pages/TarotSpreadDraw/utils/ellipse.ts
  src/router/routes.tsx
Labels: Feature

#47 Feat/mypage record kym
  public/Rive/magic_globes.riv
  src/App.tsx
  src/common/components/Loading.tsx
  src/common/store/cardStore.ts
  src/pages/Mypage/components/Likes.tsx
  src/pages/Mypage/components/Management.tsx
  src/pages/Mypage/components/Post.tsx
  src/pages/Mypage/components/Record.tsx
  src/pages/Mypage/components/RecordDetail.tsx
  src/pages/Mypage/components/RecordItem.tsx
  src/pages/Mypage/components/Sidebar.tsx
  src/pages/Mypage/index.tsx
Labels: Feature, Design, Refactor

#65 fix : 타로 스프레드 애니메이션 수정
  src/pages/TarotSpreadDraw/components/Spread.tsx
Labels: Fix
